[package]
name = "bulge"
version = "0.1.0"
authors = ["Evie Viau <evie@uwueviee.live>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rusqlite = "0.25.3"
reqwest = "0.11.4"
sudo = "0.6.0"
text_io = "0.1.9"
kdl = "1.1.0"
b2sum = "0.4.0"
xdg = { git = "https://github.com/whitequark/rust-xdg.git" }
tokio = { version = "1.10.1", features = ["rt", "macros"] }
sha2 = "0.9.5"
hex-literal = "0.3.3"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"